sudo: required
services:
  - docker

before_install:
  - docker build -t rudydydy/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rudydydy/react-test npm test -- --coverage

after_success:
  - docker build -t rudydydy/complex-client ./client
  - docker build -t rudydydy/complex-nginx ./nginx
  - docker build -t rudydydy/complex-server ./server
  - docker build -t rudydydy/complex-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push rudydydy/complex-client
  - docker push rudydydy/complex-nginx
  - docker push rudydydy/complex-server
  - docker push rudydydy/complex-worker
